### ISSUE TITLE
quan library as submodule

### ISSUE THREAD

**Issue by crashmatt** [kwikius/mixer_lang#1]
Instead of having quan as ań extra dependency and path to setup, add it as a git submodule

**Comment by crashmatt** [comment]
See pull request
https://github.com/kwikius/mixer_lang/pull/2

**Comment by kwikius** [comment]
@crashmatt 
I never understood submodules. Can they be optional? I always seem to find that, once submodules are installed, you have to delete your submodules, keep running submodule update whenever you switch branches which is more PITA than just waiting for an error message. I take much pains not to make breaking changes in quan and its use here is pretty minor. Usually the only issue is a new header that isnt found. Maybe I should version quan though!
What are your plans with this? Are you planning to do a Bison version (which might be better for a GCS than mine which is trying to be optimised for small onboard microcontrollers)

**Comment by kwikius** [comment]
Actually I am more inclined to just copy the relevant source into this library (change the namespace) and remove the dependency on quan. What do you say? ( you may guess I dont really like submodules !)

**Comment by kwikius** [comment]
I resolved this by removing the quan dependencies
https://github.com/kwikius/mixer_lang/pull/2#issuecomment-283706893
